on:
  workflow_dispatch: ~
  push:
    branches: [main]
  pull_request: ~
  release:
    types: [created]
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
    outputs:
      push: ${{ steps.version.outputs.push }}
    steps:
      - uses: actions/checkout@v6
      - id: version
        run: |
          VERSION=main

          # thesis/php:php8.2
          TAGS="thesis/php:php${{ matrix.php }}"

          # thesis/php:1.0-php8.2
          # thesis/php:1.0.2-php8.2
          if [[ $GITHUB_REF == refs/tags/* ]]; then
              VERSION=${GITHUB_REF#refs/tags/v}
              MINOR_VERSION=${VERSION%.*}
              TAGS="$TAGS,thesis/php:${VERSION}-php${{ matrix.php }},thesis/php:${MINOR_VERSION}-php${{ matrix.php }}"
          fi

          echo "Version: $VERSION"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          
          echo "Docker tags: $TAGS"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "date=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          
          echo "push=${{ (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main') && github.repository_owner == 'thesis' }}" >> $GITHUB_OUTPUT
